### ISSUE TITLE
Backend: messages.srvid ist NULL für facebook-Nachrichten

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#104]
Muss für alle Services gefüllt werden.
Voraussetzung für Fix von #103 .

**Comment by MeKugel** [comment]
Bei Alben (=> Slideshows in Flypsite) wurde bei den einzelnen Bildern die srvid nicht eingetragen, das ist nun auf Staging gefixt.

**Comment by joachimgo** [comment]
im Livesystem
