### ISSUE TITLE
Nach einem Autorisierungsfehler bleibt der Instagram-Kollektor dauerhaft im Error-State

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#11]
... auch wenn der Grund des Fehlers behoben ist.

Kunde autorisiert den Kollektor.
Kunde ändert das Login auf Seiten Instagrams (aus Gründen jenseits von FlypSite).
Offenbar ist dann das Token auch nicht mehr gültig, es gibt einen Fehler in FlypSite.

Von diesem Punkt an kann ich Autorisierungen löschen, neu zuweisen, etc. - es nützt nichts, der Fehler bleibt bestehen.
(Anmerkung aus Admin-Perspektive: Ein Restart des collector2 behebt das Problem.)

**Comment by flypsite** [comment]
in Release 2.2.1 gefixt
