### ISSUE TITLE
Initiale Nachrichten werden nicht veröffentlicht

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#110]
v.a. bei der Liste Chateingabe ärgerlich, weil so der Chat nicht mehr eingeschaltet werden kann.

Workaround: Die in der Chateingabe vorhandene Nachricht im Publisher noch einmal veröffentlichen.
![google chrome057](https://cloud.githubusercontent.com/assets/5509067/24142784/f387c19a-0e27-11e7-9bbc-b42ae9a004d5.png)

**Comment by flypsite** [comment]
erledigt
