### ISSUE TITLE
Neu angelegte Events werden nicht "aktiv"

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#118]
Trotz Startzeit und Dauer zeigt der Event nicht an, dass er aktiv ist.
Nach 24 Stunden werden die Kollektoren beendet.

Beispiel: 2038

**Comment by joachimgo** [comment]
Habe Event 2038 jetzt manuell in der Datenbank auf "aktiv" gesetzt. Bitte überprüfen, warum das beim Anlegen nicht passiert ist.

**Comment by MeKugel** [comment]
Nicht reproduzierbar.
