### ISSUE TITLE
Facebook-Kommentare an einzelnem Post: Laufen initial ein, dann nicht mehr

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#12]
Beispiel: https://www.facebook.com/AntenneNiedersachsen/photos/a.103380452149.113016.54592322149/10153686600277150/?type=1&theater
gesammelt mit der ID 10153686600277150 als 'post-comments'.

**Comment by joachimgo** [comment]
Habe gerade testweise das comments-Häkchen an post-comments gesetzt: Ein weiterer Post ist eingelaufen, die aktuellsten fehlen aber weiterhin...

**Comment by joachimgo** [comment]
im Graph-API-Explorer kriege ich aktuelle Comments zu einem Post mit `fields=comments.order(reverse_chronological)`. Bitte im Code prüfen, ob das so abgerufen wird:

https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=10153686600277150%3Ffields%3Dcomments.order(reverse_chronological)%7Battachment%2Ccreated_time%2Cfrom%2Clike_count%7D

**Comment by flypsite** [comment]
im Release 2.2.1 gefixt.
