### ISSUE TITLE
Teaser Layout (Classic) berücksichtigt Bildausschnitt nicht

### ISSUE THREAD

**Issue by maotv** [flypsite/general#13]
Die Überschrift sagt alles.

**Comment by MeKugel** [comment]
Ist gefixt, auf Staging zu testen

**Comment by joachimgo** [comment]
Das Teaser-Layout hat im Classic-Client eine besondere Optik, die bei der Überarbeitung kaputt gegangen ist.

in size "base" Bild und Text waagerecht nebeneinander.
in size "double" Bild und Text senkrecht übereinander.

jeweils 50%/50%.

Im Listenclient ist Teaser dasselbe wie image_text_link und hat keine besondere Aufteilung.
Im Teaserclient keine Sonderbehandlung (Layouts werden dort ignoriert).
Im Responsive Tiles bitte gucken; vermutlich so wie classic.

**Comment by bigbasspic** [comment]
Jetzt RICHTIG gefixt, bitte auf Staging testen.

**Comment by CleaKaechele** [comment]
In size "base" alles OK. 
Soll der gesetzte Bildausschnitt ins Overlay/Listenansicht weitergereicht werden oder nicht?
in size "double" wird das Bild zu weit links positioniert. Außerdem wird der Bildausschnitt nicht übernommen.

**Comment by CleaKaechele** [comment]
ist gefixt auch auf staging.
