### ISSUE TITLE
Special/Reports: Reports lassen sich nicht generieren

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#14]
Es ist nicht möglich, einen Report eines aktuellen Events zu generieren. 

Das gilt sowohl für die Funktion "Report für Event generieren" als auch mit händisch eingegebenen Zeiten.
Probiert bei Badische Zeitung, bergungpolizeiauto.

**Comment by maotv** [comment]
ArithmeticException: Thrown when an exceptional arithmetic condition has occurred. 
(== division by zero?). Zusätzlich dann noch eine Ungenauigkeit bei der Integer-Division.
Hat nicht alle Event betroffen, vermutlich aber alle bei denen ein Client gar keine Zugriffe hatte.
Ist behoben in lumiere-11-g3b83fa8 (installiert auf duck)
