### ISSUE TITLE
Publisher: HTML-Code in Facebook-Nachricht wird nicht richtig escaped/gestrippt

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#15]
HTML-Code in Nachrichten sollte bereits serverseitig entfernt oder wirkungslos gemacht werden. Das ist offenbar nicht der Fall.

Bild 1: Ansicht im Publisher
![google chromescreensnapz094](https://cloud.githubusercontent.com/assets/5509067/9586407/00ce3af2-501d-11e5-81e5-e2714d9c896d.jpg)

Bild 2: Ansicht im Publisher nach Klick auf Editieren und dann auf Abbrechen. Nach reload wieder wie Bild 1.
![google chromescreensnapz095](https://cloud.githubusercontent.com/assets/5509067/9586396/ec2e13f6-501c-11e5-83f6-0c216eb64a77.jpg)

**Comment by maotv** [comment]
das ist doch längst gefixt, oder?

**Comment by MeKugel** [comment]
gefixt und live, ja
