### ISSUE TITLE
Extension/Bookmarklet: Einsammeln von bestimmten URLs macht Probleme

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#16]
URLs von https://babyundjunior.de lassen sich partout nicht einsammeln. Woran liegt's?

Z.B. https://babyundjunior.de/de/Kind-Jugend/Aktuelle-Nachrichten/Die-Nominierten-fuer-Koeln

Es läuft keine Nachricht im Backend ein.

**Comment by joachimgo** [comment]
Vielleicht steigt unser Parser deswegen aus:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fbabyundjunior.de%2Fde%2FKind-Jugend%2FAktuelle-Nachrichten%2FDie-Nominierten-fuer-Koeln

(eine ganze Reihe von HTML-Errors...)

**Comment by joachimgo** [comment]
Mit einer tagesschau.de-Seite mit zahlreichen Errors kommt die Extension aber zurecht...:

https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.tagesschau.de%2Fausland%2Fungarn-zuege-105.html

**Comment by MeKugel** [comment]
Das Problem entstand durch einen Certificate Fehler im Server (nicht vertrauenswürdiges SSL Certificate). Vermutlich ist das Certificate noch so neu, dass es noch nicht an alle Stellen verteilt ist. Solange das Problem nicht mit anderen Certificates (die älter als ca. ein Monat sind) auftritt, wird der Bug als temporäres Problem eingestuft.
