### ISSUE TITLE
Drag & Drop Editor: Nachrichten aus abonnierten Listen können nicht veröffentlicht werden.

### ISSUE THREAD

**Issue by bigbasspic** [flypsite/general#17]
D&D nutzt eine "update" Funktion, muss aber in diesem Fall mit einer Kopie der Nachricht arbeiten.

**Comment by joachimgo** [comment]
Handling von abonnierten Listen wurde modifiziert. Ist das auch gefixt?

**Comment by maotv** [comment]
Nein, ist noch nicht gefixt, das ist ein größerer Umbau des D&D Publishers.

**Comment by joachimgo** [comment]
Workaround vorhanden: die abonnierte Liste mit dem Plumber in eine eigene Liste weiterleiten und dabei  "clone message" aktivieren. Die eigene Liste zum Veröffentlichen nutzen.
