### ISSUE TITLE
Instagram-Collector: "sammelt nicht"

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#19]
Schon zum zweiten Mal beobachten wir, dass Instagram-Nachrichten trotz laufendem Collector nicht eingesammelt werden.
Nach einem Collector2-Neustart ist alles OK.

Event: einstein-marathon2015.swp
Jeweils Sonntag-Morgen, 20./27.09., ca. 09:00 Uhr. Die Redaktion hat dann per Extension eingesammelt, bis der Collector restartet wurde.

**Comment by MeKugel** [comment]
war das ein einmaliges Phänomen oder trat das Problem öfters auf? rotten?

**Comment by joachimgo** [comment]
rotten
