### ISSUE TITLE
Autoforward funktioniert für alte Sources nicht mehr

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#20]
adlermannheim.morgenweb: das Autoforward auf der Quelle @adlermannheim hat seit 24.08.2015 nicht geforwardet.
Eine neuangelegte Quelle mit Autoforward leitet auch nicht weiter, wenn ich nicht zusätzlich das Plumbing aktualisiere (auf der Seite Plumber).

**Comment by maotv** [comment]
Gefixt im releasebranch (merge_playout_ng) und im masterbranch, bitte testen und schliessen

**Comment by maotv** [comment]
ausprobiert: geht
