### ISSUE TITLE
Autoforward auf Sources lässt sich nicht ausschalten

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#23]
forwardSourceMessages mit stream=0 - wird das richtig behandelt?

![Debug-Info](https://cloud.githubusercontent.com/assets/5509067/10820946/17bd4e40-7e50-11e5-869b-b5b41343397c.jpg)

Nach Plumber-"Änderungen übernehmen" ist dann alles OK

**Comment by maotv** [comment]
Sieht so aus als ob die 0n bisher nicht richtig kommuniziert worden ist (SourceHandler.java #144). Es flog eine Exception weil mit 0 kein Stream gefunden wurde, dieser aber im Verlauf genutzt wurde. Ich habe das geändert. => keine Exception mehr. Getestet im Plumber via debugfunktion.
