### ISSUE TITLE
Instagram: API changes angekündigt

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#26]
http://developers.instagram.com/post/133424514006/instagram-platform-update

**Comment by MeKugel** [comment]
Die einzige Änderung, die uns betrifft, ist die, dass alle Apps noch einmal reviewed werden müssen. Die Möglichkeit dazu ist ab dem 3.12.2015 verfügbar und wir werden dies auch schnellstmöglich machen.

**Comment by joachimgo** [comment]
Was ändert sich wirklich für uns?

https://instagram.com/developer/changelog/

**Ab Juni 2016 bzw. beim Erstellen einer neuen App ab sofort gelten die folgenden Anforderungen:**

Start in Sandbox mode for dev & test
Need to be reviewed and permission scopes approved before used in production
**Updates an der Instagram-App werden kompliziert, keine Änderungen ohne Review.**
All API endpoints require a valid access_token
**Keine Änderung**
All API endpoints require a specific permission scope granted by the user
**Neu, muss implementiert werden.**
New follower_list permission scope
New public_content permission scope
New rate limits for Sandbox and Live apps
**Klären, was das für _Live apps_ konkret bedeutet. 5.000 req/Stunde und angemeldetem User?**
Private content only available to content owner
**Keine Änderung**
Deprecation of /users/self/feed
**Nicht genutzt in FlypSite**
Deprecation of /media/popular
**Nicht genutzt in FlypSite**
Deprecation of /geographies/media/recent
**Nicht genutzt in FlypSite**
Deprecation of Realtime subscriptions for tags, locations and geographies
**Nicht genutzt in FlypSite**
API responses containing media objects no longer return the data field in comments and likes nodes
**Nicht genutzt in FlypSite**

Außerdem werden ab Juni auch nicht-quadratische Bilder ausgeliefert. Die Option kann heute bereits aktiviert werden.
**Umstellung Server-/Clientcode, falls diese bei Instagram Bildern von 1:1-Seitenverhältnis ausgeht.**
