### ISSUE TITLE
FlypCaster: v1.1.0 skaliert Dialoge im Vollbildmodus falsch

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#27]
FlypCaster Update 1.1.0 stellt die Anzeige von Dialogen auf einen Java-internen Modus um. 

Im OSX-Vollbildmodus werden die Dialoge nun auch auf Vollbild skaliert, was nicht gewünscht ist. Nach Zurückschalten in den Normalmodus werden die Dialoge weiter auf Vollbild skaliert.
Update 1.1.0 ist noch nicht ausgeliefert.

**Comment by joachimgo** [comment]
Noch ein paar Tests:
Fehler tritt auf auf OSX El-Capitan, Yosemite (beide mit Java 1.8.0_66).
Windows: Keine Probleme. (Windows 8, Java 1.8.0_66)

**Comment by maotv** [comment]
Ich habe mir das angeguckt und bin etwas ratlos was wir tun sollen. WONTFIX? Ich würde gern den nativen Fullscren-Mode von OSX ausschalten können (oder den fullscreen-button des Fensters ganz wegnehmen), habe aber in einer ersten kurzen Recherche noch keinen Weg gefunden um das zu tun.

**Comment by joachimgo** [comment]
Der Settingsdialog wird nicht auf volle Bildschirmgröße skaliert, nur der Event-Auswahldialog. Wenn das kein Weg ist, dann WONTFIX. Natives Fullscreen würde ich nicht wegnehmen.

**Comment by joachimgo** [comment]
WONTFIX
