### ISSUE TITLE
Neu angelegte öffentliche Listen werden nicht über https ausgespielt

### ISSUE THREAD

**Issue by bigbasspic** [flypsite/general#29]
Legt man in einem bereits angelegten Event eine neue öffentliche Liste an, wird diese nicht über flypsite.appspot.com ausgeliefert. Man muss diesen Event nochmals migrieren, dann aber Bug #30

**Comment by maotv** [comment]
Wenn der Stream mit "New public Stream" angelegt wird, ist er öffentlich verfügber sobald mindestens eine Nachricht in den Stream publiziert wird. Das Umschalten von Streams (private->public) geht nicht, die initial.json ist auf der appengine dann nicht verfügbar.

**Comment by joachimgo** [comment]
Anmerkung für Motus auf flyp_streams.php ergänzt (Öffentliche Listen müssen als solche angelegt werden, umschalten funktioniert nicht.).

**Comment by bigbasspic** [comment]
Gilt Götterseidank nicht für die Ausspielung auf ein Moderator-IPad. Da kann man eine private Liste öffentlich schalten, und es funktioniert.
