### ISSUE TITLE
Wenn der Event migriert wird, funktionieren die einem Client zugewiesenen Streams ("Single Stream") nicht mehr

### ISSUE THREAD

**Issue by bigbasspic** [flypsite/general#30]
Ein Client hat einen Stream zugewiesen bekommen, den er als einzigen ausspielen soll. Nach dem Anlegen eines neuen public Streams und einer nachfolgenden Migration (damit der Stream in der Ausspielung auftaucht siehe Bug #29 ), werden für diesen Client alle Streams ausgespielt.
Spielt man den Client danach nochmal aus, funktioniert es wieder wie gewollt.

**Comment by joachimgo** [comment]
Bitte einmal für https-only und einen neuen Event überprüfen.

**Comment by joachimgo** [comment]
Zu viele Voraussetzungen, die heute nicht mehr zutreffen.
