### ISSUE TITLE
Neue Events: im Dashboard bleibt die Anzahl der Nachrichten dauerhaft auf 0, auch wenn Nachrichten gesammelt wurden. 

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#32]
gilt für jeden neu angelegten Event, z.B. http://welovehh.journal.flyp.tv/

**Comment by MeKugel** [comment]
Die Anzahl wird nur ein mal pro Stunde aktualisiert. Bleibt die Anzahl länger als 1 std. nach Erstellen des Events auf 0?

**Comment by joachimgo** [comment]
schon länger gefixt
