### ISSUE TITLE
Social Stream lässt sich im D&D nicht befüllen.

### ISSUE THREAD

**Issue by annuk36** [flypsite/general#33]
Social Stream lässt sich im D&D nicht befüllen. Über Publisher ist es möglich. Kleiner Umweg...
http://us-vorwahliowa.admin.flyp.tv/

**Comment by joachimgo** [comment]
Bitte überprüfen, was die Console-Ausgabe "Server error! no message" bedeutet und wer das bearbeiten soll.

**Comment by joachimgo** [comment]
Gilt vermutlich auch für die Chateingabe.

**Comment by CleaKaechele** [comment]
Social Stream und Chateingabe wurden im D&D Editor entfernt. Den Socialstream kann man über den Quickpublish Button befüllen, die Chateingabe über den Publisher.
