### ISSUE TITLE
Vienna: message-Envelopes verhalten sich unterschiedlich bzgl. des Attributs stream

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#36]
envelopes enthalten "stream" in der Pusher-Auslieferung, sie enthalten das Attribut nicht in der stream-initial.
Soll: envelopes sollten dieselben Informationen enthalten, unabhängig vom Auslieferungsweg.

**Comment by joachimgo** [comment]
Vgl. auch #41 .

**Comment by maotv** [comment]
die stream initials enthalten (seit ???) das feld "stream" im envelope. Das Thema einheitliche message-ausspielung bleibt aber aktuell (siehe #41)
