### ISSUE TITLE
Twitter-Sammler: Retweets und Unwrap-Funktion sind broken

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#38]
Hier sind offenbar zwei Dinge kaputt:
1. Retweets werden nicht eingesammelt, auch wenn das "rt"-Häkchen an ist. Ebenso funktioniert die Unwrap-Funktion nicht, wenn das "uw"-Häkchen an ist. (Getestet in Sources für den user @irgendwas und Retweets von @irgendwas, sowie #irgendwas)
2. Seit einiger Zeit hat Twitter die Funktion "Tweet zitieren", was gefühlt ein Retweet mit Kommentar ist, praktisch jedoch nur ein normaler Tweet mit einem t.co-Link auf den Originaltweet. Hierzu gibt es noch keine FlypSite-Policy: Kann/soll das als Retweet gelten? Soll Unwrap funktionieren?

getestet in qatest.jo im Livesystem.

**Comment by MeKugel** [comment]
gefixt, bitte testen

**Comment by joachimgo** [comment]
works.
ad 1.: Alte Funktionalität wieder hergestellt.
ad 2: ein "Quote" wird wie ein Retweet behandelt. D.h.: 
- läuft nicht ein, wenn rt und uw aus sind
- bei aktiviertem rt läuft der Tweet mit t.co-Link ein
- bei aktiviertem uw läuft der Originaltweet (der aus dem t.co-Link) ein
