### ISSUE TITLE
classic/classic1080: Client verspringt wenn man den den SocialStream öffnet (und wieder schließt)

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#44]
Der Effekt ist kaum sichtbar, wenn man nicht gescrollt hat. Wenn man ein ganzes Stück scrollt und dann den SocialStream öffnet, kann man anschließend die FlypSite nicht mehr bis oben scrollen.

**Comment by bigbasspic** [comment]
Fixed. Please check.

**Comment by joachimgo** [comment]
fixed
