### ISSUE TITLE
Client-Builder: Fehler bei Symlink

### ISSUE THREAD

**Issue by bigbasspic** [flypsite/general#45]
Die Property "symlink" in der Client-Config-JSON scheint sich auf den letzten Eintrag des Hashes auszuwirken, nicht auf den, in dem sie steht. 
Beispiel: v3_twolist.json, wenn der Eintrag der growing.js an letzter Stelle steht, wird diese mit dem Symlink verlinkt.

**Comment by MeKugel** [comment]
gefixt auf Staging
