### ISSUE TITLE
Facebook video Import generiert relativen Link.

### ISSUE THREAD

**Issue by maotv** [flypsite/general#50]
Facebook video Import via extension  generiert relativen Link.
https://www.facebook.com/ESCOesterreich/posts/498999140303042

ZOE sings "Play" by Jüri Pootsmann
Challenge unter den Künstlern: Sing das Lied des Landes, das nach dir im Semi Finale antritt und teile es auf deren Facebook Seite #esc2016 #singtogether
Link:/zoemusicofficial/videos/498347620369126/

**Comment by MeKugel** [comment]
ist gefixt
