### ISSUE TITLE
Backend: Anlegen eines public streams erfordert noch restart des Playout-Prozesses

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#51]
... sonst kommen die Nachrichten des neuen Streams nicht in der initial.json an.

Steps:
- neuen public stream anlegen
- im publisher eine Nachricht in diesen Stream veröffentlichen
- initial.json checken: die Nachricht ist dort nicht vorhanden

**Comment by maotv** [comment]
Anlegen mit "New public stream" geht.
Umschalten zw. public & private ist nur für motus und geht nicht ohne neustart.

Kann der Bug geschlossen werden?

**Comment by joachimgo** [comment]
In einem "public" angelegten Stream geht jetzt alles wie es soll.
