### ISSUE TITLE
ts-Video wird falsch importiert

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#53]
tweet heute 09:47 (Unwetter) oder diese URL per Medienklammer: http://www.tagesschau.de/multimedia/livestreams/livestream1/index.html

vgl. admin/isthereapinarea

**Comment by joachimgo** [comment]
gilt auch für on-demand-Videos, z.B. http://www.tagesschau.de/inland/bericht-vom-parteitag-linkspartei-101.html

im iFrame ist keine source gesetzt.

**Comment by joachimgo** [comment]
Bitte überprüfen, ob das im Backend oder im Frontend-JavaScript schiefgeht.

**Comment by MeKugel** [comment]
Momentan fehlt die Syntax für die Player URL, daher können aus Tagesschau Video URLs keine Player URLs generiert werden.

Im Backend wird für on-demand der Sophora-Key gespeichert, für live noch nicht. Eine av_url oder av_playerurl wird nicht gespeichert.

**Comment by MeKugel** [comment]
Für on-demand Videos wird nun wieder eine funktionierende Player URL generiert. Livestreams sind fürs Erste nicht verfügbar.

Auf Staging testbar.

**Comment by joachimgo** [comment]
Tests in der TagesschauRessource-Klasse ergänzt. Bitte weiter bearbeiten.

**Comment by joachimgo** [comment]
TagesschauRessource, Stand heute bildet den aktuell möglichen Stand ab. Closed.
