### ISSUE TITLE
scribble-Collector: erste Source-Zeile funktioniert nicht

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#54]
Der momentane Zustand eines neu angelegten Collectors zeigt initial eine nicht-existente Source an... Speichern etc. geht natürlich schief. Bitte entweder eine valide Source einfügen, oder initial keine Source anzeigen.

**Comment by MeKugel** [comment]
diese "Geister"-Source wird nun nichtmehr angezeigt
