### ISSUE TITLE
Was ist das?

### ISSUE THREAD

**Issue by maotv** [flypsite/general#55]
WARNING: Attempting to re-send the request to flyp-tv-clients.s3.eu-central-1.amazonaws.com with AWS V4 authentication. To avoid this warning in the future, please use region-specific endpoint to access buckets located in regions that require V4 signing.
Jun 09, 2016 11:13:43 PM com.amazonaws.services.s3.internal.S3V4AuthErrorRetryStrategy buildRetryParams
WARNING: Attempting to re-send the request to flyp-tv-clients.s3.eu-central-1.amazonaws.com with AWS V4 authentication. To avoid this warning in the future, please use region-specific endpoint to access buckets located in regions that require V4 signing.
Jun 09, 2016 11:13:43 PM com.amazonaws.services.s3.internal.S3V4AuthErrorRetryStrategy buildRetryParams
WARNING: Attempting to re-send the request to flyp-tv-clients.s3.eu-central-1.amazonaws.com with AWS V4 authentication. To avoid this warning in the future, please use region-specific endpoint to access buckets located in regions that require V4 signing.
Jun 09, 2016 11:13:44 PM com.amazonaws.services.s3.internal.S3V4AuthErrorRetryStrategy buildRetryParams
WARNING: Attempting to re-send the request to flyp-tv-clients.s3.eu-central-1.amazonaws.com with AWS V4 authentication. To avoid this warning in the future, please use region-specific endpoint to access buckets located in regions that require V4 signing.

**Comment by joachimgo** [comment]
Bitte klären und Bug-Titel/Beschreibung anpassen.

**Comment by maotv** [comment]
lange erledigt
