### ISSUE TITLE
Facebook Api Changes!

### ISSUE THREAD

**Issue by maotv** [flypsite/general#56]
Graph API v2.1 Upgrade NoticeAchtung
FlypSite Publisher has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences.

We recommend using our new Graph API Upgrade Tool to see which of your calls are affected by this change as well as any replacement calls in newer versions. You can also use our changelog to see the full list of changes.

**Comment by joachimgo** [comment]
Bitte möglichst auf v. 2.6 updaten. 
Änderungen siehe hier: https://developers.facebook.com/tools/api_versioning/753259058035894 (API Upgrade Tool)

**Comment by MeKugel** [comment]
Aktuell ist alles auf Version 2.6 umgestellt
