### ISSUE TITLE
Move ypics to Frankfurt

### ISSUE THREAD

**Issue by maotv** [flypsite/general#57]
1) Neuen Bucket in Frankfurt anlegen: flyp-tv-ypics
2) flyp-ypics ordner-für-ordner von Irland nach Frankfurt kopieren
3) flypsite umkonfigurieren auf  flyp-tv-ypics, fabians hacks aus dem Code rausnehmen
4) flyp-ypics löschen oder umbenennen um klar zu machen welcher bucket gilt

**Comment by MeKugel** [comment]
alle Punkte abgehakt
