### ISSUE TITLE
Chrome-Extension: "no message"

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#62]
Die Chrome-Extension lässt sich im Flyp-Backend auf einen Event einrichten.
Beim Einsammeln (Website, Twitter) produziert sie neuerdings verlässlich den Fehler

Es ist ein Fehler aufgetreten!
no message

Die Firefox-Extension geht.

**Comment by MeKugel** [comment]
Der Fehler ist nicht reproduzierbar. Bitte nochmal testen und überprüfen, ob es lokal an Chrome liegt

**Comment by joachimgo** [comment]
Zwei Rechner, Fehler auch nach Neuinstallation der extension

Am Mittwoch, 29. Juni 2016 schrieb MeKugel :

> Der Fehler ist nicht reproduzierbar. Bitte nochmal testen und überprüfen,
> ob es lokal an Chrome liegt
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/flypsite/general/issues/62#issuecomment-229295506,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFQPy9k6M81Yc58Wz8IvayizUpU_fxOlks5qQjFVgaJpZM4JAYLx
> .

## 

Sent from Gmail Mobile

**Comment by joachimgo** [comment]
Browser-Neustart, dann OK
