### ISSUE TITLE
Special/CSS-Editor nicht erreichbar

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#63]
Server error: no message

**Comment by MeKugel** [comment]
Über einen Zeitraum von ca 10 Minuten waren im Log Exceptions in dem Bereich zu finden. Danach und davor war alles gut. Der Fehler tritt auch nicht mehr auf. Ich würde es für ein temporäres Problem bei Amazon halten.

**Comment by joachimgo** [comment]
geht
