### ISSUE TITLE
Scroll to Top Button - richtig positionieren

### ISSUE THREAD

**Issue by CleaKaechele** [flypsite/general#65]
Der Scroll to Top Button muss wieder richtig positioniert werden. 
Siehe z.B. hier: https://live.flyp.tv/flypsite/flypstream/out1.html

**Comment by joachimgo** [comment]
Beim Verändern der Breite des Browserfensters rutscht der Top-Button über die Liste. Initial und beim Scrollen wird er richtig positioniert.

**Comment by joachimgo** [comment]
fixed, live
