### ISSUE TITLE
Google+-Kollektor nicht mehr standard-mäßig anlegen in neuen Events?

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#66]
auf Wunsch könnte er von 4=1 immer noch einem Event zugeordnet werden, so wie auch Scribble/Slack .

Grund:
G+ wird so gut wie gar nicht genutzt.

**Comment by bigbasspic** [comment]
Google-Collector entfernt. Wirkt nur bei neu angelegten Events.

**Comment by joachimgo** [comment]
Danke
