### ISSUE TITLE
Animierte GIFs aus Twitter werden als PNG in FlypSite importiert (und nicht mehr animiert ;-(

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#7]
Grund: Twitter stellt GIFs wohl selbst als Videos dar. Beim Import beachten!

**Comment by joachimgo** [comment]
Discussion: 
- https://twitter.com/twitterdev/status/479311209565413376
- https://twittercommunity.com/t/adding-animated-gifs-via-rest-and-streaming-apis/30070

**Comment by flypsite** [comment]
in Release 2.2.1 gefixt
