### ISSUE TITLE
Twolist: Banner verspringt bei Updates auf der Seite

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#70]
Hat das Bild im Banner eine im Bildeditor angegebenen Bildausschnitt, so führen beliebige Updates auf der Seite dazu, dass das Bannerbild verspringt. Bei Reload ist wieder alles gut...

Updates, die für den Fehler sorgen:
- Einlaufen einer neuen Nachricht
- Weiterscrollen

https://live.flyp.tv/admin/googlealerts/index.html

**Comment by joachimgo** [comment]
oh, der Effekt tritt übrigens nicht auf, wenn das Video nicht sichtbar ist. (Da wird offenbar das Resizing nicht getriggert.)

**Comment by bigbasspic** [comment]
Nun nicht mehr.

**Comment by joachimgo** [comment]
Gut
