### ISSUE TITLE
Facebook Collector-Aktualisierung ist fehlerhaft

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#75]
Im Motu-Aufklapper kriege ich folgende Ausgabe, wenn ich
- erst eine unsinnige ID eingebe (10:29)
- dann eine existierende User-ID eingebe (10:31)

Die unsinnige ID ist nicht mehr eingetragen...

```
19.7.16 10:43:32    1403        Dieser Alias ist Facebook unbekannt (joachim.gola)  Received Facebook error response of type OAuthException: (#803) Some of the aliases you requested do not exist: 68165896126129876 (code 803, subcode null)
19.7.16 10:32:00    200
19.7.16 10:31:32    1403        Dieser Alias ist Facebook unbekannt (joachim.gola)  Received Facebook error response of type OAuthException: (#803) Some of the aliases you requested do not exist: 68165896126129876 (code 803, subcode null)
19.7.16 10:30:11    200         
19.7.16 10:29:32    1403        Dieser Alias ist Facebook unbekannt (68165896126129876) Received Facebook error response of type OAuthException: (#803) Some of the aliases you requested do not exist: 68165896126129876 (code 803, subcode null)
```

**Comment by joachimgo** [comment]
vgl. #67

**Comment by CleaKaechele** [comment]
Anmerkung 1 : Private User Seiten können nicht eingesammelt werden. Fehlermeldung nicht korrekt. 
![bildschirmfoto 2016-07-28 um 11 42 06](https://cloud.githubusercontent.com/assets/12541943/17208308/7229f664-54b8-11e6-9cc1-ac317941131d.png)

**Comment by CleaKaechele** [comment]
Anmerkung 2: 
Wenn eine unsinnige ID eingegeben wurde und danach eine andere unsinnige ID eingegeben wird, dann wird in der Fehlermeldung die erste unsinnige ID dargestellt. 

![bildschirmfoto 2016-07-28 um 11 34 40](https://cloud.githubusercontent.com/assets/12541943/17208759/3bb85628-54ba-11e6-880e-1b27fa4f6f17.png)

**Comment by joachimgo** [comment]
Das sieht jetzt viel besser aus. Die og. Probleme sind aus meiner Sicht behoben.
Allerdings hier noch eine Bitte:

Die beiden Fehlermeldungen im Screenshot sind in der letzten Spalte klar unterscheidbar: oben: wir können keine userfeeds einsammeln, unten: die Seite existiert nicht.

Wäre schön, wenn das auch als Fehlermeldung zum Author durchdringt.

![screenshot 2016-08-01 16 33 37](https://cloud.githubusercontent.com/assets/5509067/17297401/db554c42-5805-11e6-9d9e-6d8a2954855b.png)

**Comment by MeKugel** [comment]
Fehlertext so geändert, dass er beide Fälle abdeckt.
