### ISSUE TITLE
Twitter-Collector: Fehler auf Source-Ebene anzeigen

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#76]
vgl. #74 

Verbesserung: auch in twitter die Fehlermeldungen den einzelnen Sources zuordnen und die Fehlermarkierung an den Sources vornehmen.

**Comment by joachimgo** [comment]
Mögliche Fehleranzeigen:
- type=List: username/listenname kann nicht abgerufen werden, weil eines der beiden nicht stimmt
- type=Users: Username kann nicht abgerufen werden (nicht existent/private, ...)
- type=Hashtags: ?

**Comment by MeKugel** [comment]
ist eingebaut
