### ISSUE TITLE
Medienklammer/Extension: mp4-URLs zu media auflösen

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#79]
Direkte URLs auf mp4-Dateien sollen als av-Media angelegt werden.

**Comment by MeKugel** [comment]
Per Medienklammer angehängte mp4 URLs werden in das Media eingetragen und die Nachricht wird zu einer Videonachricht

**Comment by MeKugel** [comment]
ist somit eingebaut

**Comment by joachimgo** [comment]
Wird ein Bild per Medienklammer angehängt, soll das evtl. vorhandene Video nicht gelöscht werden, auch das Layout soll nicht modifiziert werden.
Wird ein Video per Medienklammer angehängt, soll ein evtl. vorhandenes Bild nicht gelöscht werden. Das Layout soll wie jetzt auch auf "video" gesetzt werden.

**Comment by joachimgo** [comment]
geht, inkl. der Ergänzung vom 28.9.
