### ISSUE TITLE
Twitter-Video: Provider twimg auch zu einem av-media-Provider machen

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#81]
Twitter-Videos wollen wir auch nutzen. Sowohl im Web als auch im FlypCaster (VLC).

vgl. admin/allvideos; auch twitter.com/heuteplus

**Comment by MeKugel** [comment]
Auch Twittervideos als Amplify-Card werden jetzt unterstützt.

**Comment by MeKugel** [comment]
ist gefixt

**Comment by joachimgo** [comment]
Das hier läuft noch als message ohne Media ein (über extension eingesammelt):

https://twitter.com/heuteplus/status/781096021300568064
https://twitter.com/heuteplus/status/780865851998150656

(admin/allvideos)

**Comment by joachimgo** [comment]
Beispiele aus Kommentar vom 28.9. gehen jetzt auch.
