### ISSUE TITLE
FE: Zwangsumschreibung auf https entfernen?

### ISSUE THREAD

**Issue by bigbasspic** [flypsite/general#84]
Problem: Wir schreiben ALLE URLs auf https um, daher können keine Streams mit http eingebunden werden (z.B. Audio-Player NDR).
Sollten wir so umstellen, dass der Server bei http-URLs checkt, ob das Video/Audio auch unter https erreichbar ist und dann die URL auf https umschreibt, und dann können wir die Umschreibung auf https im FE wegnehmen und erlauben trotzdem http-Streams.

**Comment by joachimgo** [comment]
Stand heute: Es gibt keine Zwangsumschreibung mehr. Wer sie trotzdem haben möchte, muss global

`var nohttpurls = true;`

setzen (HTML-Injection).
