### ISSUE TITLE
Classic-Client: Overlay öffnen geht nicht, wenn die Nachricht einen iFrame enthält

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#85]
vgl. Event admin/iframetest

jo!

**Comment by TobiS1** [comment]
Branch: 20161006-iframefix, fixed und getestet. 
Comment-Ecke wird beim Hover nicht angezeigt auf MSIE Browser (hover über Iframe wird nicht erkannt).

**Comment by joachimgo** [comment]
Bitte in den nächsten Release aufnehmen
