### ISSUE TITLE
RSS mit "li" aktiviert: Titel ist null

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#86]
Beim Einsammeln von http://www.immobilo.de/rss/kaufen/pullach-im-isartal?&propertytype=0&radius=2000&sort=12 via RSS mit "li" aktiviert läuft die Nachricht mit null im Titel ein.
Sammelt man eine dieser Nachrichten über die Extension ein, ist der Titel richtig gesetzt, z.B. http://www.immobilo.de/immobilien/K71460115 . 
- Titel sollte gesetzt werden. 
- null als Wert sollte grundsätzlich abgefangen werden. "" ist dann der geeignete Wert.

jO!

**Comment by joachimgo** [comment]
im Event ID 1625.

**Comment by MeKugel** [comment]
Aktuell kann ich den Bug nicht reproduzieren. Evtl. war es ein temporärer Bug bei immobilo.de. Bei Wiederauftreten des Fehlers bitte Ticket wieder öffnen.
