### ISSUE TITLE
Facebook-Collector: Gesharete Videos werden fehlerhaft eingesammelt

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#87]
Das Post
(1) https://www.facebook.com/BabyundJunior/posts/1093979340718059
teilt das Post
(2) https://www.facebook.com/627514190646863/videos/1234096846655258/

(2) können wir einsammeln, Video und Vorschaubild werden ordentlich angelegt, Layout ist video.
(1) sammeln wir als Video (Layout, Media), aber media.av und media.image sind leer.

Zwei Fixes nötig:
1. [BUG] Wenn wir keine brauchbaren Informationen von facebook kriegen, dürfen wir auch kein Video anlegen. 
2. [ENHANCEMENT] Vielleicht kriegen wir ja doch die Informationen von (2), wenn (1) einläuft. Dann sollten wir diese Informationen verwenden.

Workaround: Das Originalpost (2) einsammeln (mit der Extension) funktioniert.

**Comment by MeKugel** [comment]
1.[BUG] ist gefixt und live.

**Comment by CleaKaechele** [comment]
ich habe von dieser Seite Posts gesammelt
https://www.facebook.com/hundefreunde

Das gesharte Video wird mit Collector oder Extension nicht eingesammelt. 
Außerdem wird das User-Icon nur beim einsammeln mit der Extension dargestellt.

**Comment by joachimgo** [comment]
(1) und (2) funktionieren, komische Hunde auch...
