### ISSUE TITLE
Facebook-Collector: Nur schlecht aufgelöstes Thumbnail wird eingesammelt, ...

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#88]
... wenn mehrere Bilder am Post hängen.
[BUG] Richtig wäre, das gut aufgelöste (erste) Bild einzusammeln.
[ENHANCEMENT] Optimal wäre, alle Bilder einzusammeln und eine Slideshow daraus zu machen.

Beispielpost: https://www.facebook.com/stilundmarkt/posts/1068260216583512

(Wenn via Extension eingesammelt, ist dieses Post OK. Der Fehler tritt auf, wenn via Collector gesammelt wird.)

**Comment by CleaKaechele** [comment]
Anmerkung: 
[ENHANCEMENT] Optimal wäre, alle Bilder einzusammeln und eine Slideshow daraus zu machen. Das ist implementiert, aber bisher wird der Text des Posts nicht mit eingesammelt. 
Bitte einmal Feedback geben, ob das so soll oder ob der Text auf das erste Bild der Slideshow soll. 
Den Text auf alle Bilder zu packen, wäre redundant.

**Comment by CleaKaechele** [comment]
fixed
