### ISSUE TITLE
Facebook-Collector: Alle Bilder eines Albums einsammeln

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#89]
... und eine Slideshow draus machen:

https://www.facebook.com/dasspielzeug/posts/1123720714384759
(zeigt nur das erste Bild am Post)

**Comment by CleaKaechele** [comment]
fixed

**Comment by CleaKaechele** [comment]
Anmerkung:
Die Slideshow ist implementiert, aber bisher wird der Text des Posts nicht mit eingesammelt.
Bitte einmal Feedback geben, ob das so soll oder ob der Text auf das erste Bild der Slideshow soll.
Den Text auf alle Bilder zu packen, wäre redundant.

**Comment by joachimgo** [comment]
Es geht um das Post https://www.facebook.com/dasspielzeug/posts/1123720714384759 . Jeder Albumeintrag hat eine eigene Textmessage. Richtig wäre, die für die Albumposts anzeigen zu können. Event: admin/facebooktest .

Außerdem fällt auf, dass das "Deckblatt" des Albums fehlt. Die Message mit dem Text "Alle Jahre wieder: Wie bereits 2015 feierten wir auch in diesem Jahr Weihnachten bereits im August und stellten Euch 31 Tage lang aktuelle Kalender vor. In diesem Fotoalbum und auf unserer Webseite findet ihr alle Adventskalender in der Übersicht: http://bit.ly/2eITJc2" ist nicht zu sehen.

**Comment by joachimgo** [comment]
"Deckblatt" gibt es nicht. (Die Trägernachricht wird nicht dargestellt, nur die Nachrichten des angehängten Streams.)
Albumbilder werden eingesammelt und zu vollständigen nachrichten verarbeitet (inkl. evtl. Texte).
