### ISSUE TITLE
Neue Probleme mit Facebook: User-Posts auf FB-Pages

### ISSUE THREAD

**Issue by flypsite** [flypsite/general#9]
Bei User-Posts auf "offenen" Facebook-Seiten kann FlypSite derzeit keine Bilder einsammeln (11.07.2015). Posts des Seitenbesitzers sind unproblematisch.

Leider lassen sich die fraglichen Posts auch nicht via Extension einsammeln.

**Comment by joachimgo** [comment]
Bisher keine Lösung in Sicht. Das Problem scheint nicht bei allen User-Posts aufzutreten; wir haben keinen Workaround gefunden, da die FB-API die fraglichen Posts nicht ausliefert.
