### ISSUE TITLE
Facebook-Collector: Eingabe einer vollständigen URL zur Konfiguration einer Quelle ermöglichen

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#96]
vgl. #95 - der ID-Teil, der die Page beschreibt, ist für den Kunden nicht selbst ableitbar.
Andererseits kann unsere Programmlogik eine vollständige URL auflösen.

New feature: eine vollständige URL zur Konfiguration ermöglichen (zusätzliche Option).

**Comment by joachimgo** [comment]
Auf staging getestet und die Strings (lang/collector_de.js) angepasst.

**Comment by joachimgo** [comment]
Muss noch ausgeliefert werden

**Comment by MeKugel** [comment]
ist auf Live ausgeliefert
