### ISSUE TITLE
Subscription: Abonnement löschen ermöglichen

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#97]
Die abnehmende Seite muss "unsubscriben" können (bisher: not yet implemented).

**Comment by joachimgo** [comment]
getestet, Strings modifiziert ("not yet implemented" raus)

**Comment by joachimgo** [comment]
Muss noch ausgeliefert werden.

**Comment by MeKugel** [comment]
ist auf Live ausgeliefert
