### ISSUE TITLE
Darstellung von Tweets fehlerhaft?

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#98]
Es gibt Fälle, wo das Bild des Tweets nicht, stattdessen ein Logo dargestellt wird. Vgl. Screenshot, der Tweet ist hier: https://twitter.com/PolizeiHamburg/status/807194224982683649

vgl. Event journal/osze

![google chrome021](https://cloud.githubusercontent.com/assets/5509067/21057755/29de7ac8-be3b-11e6-8198-ef7bc13754ea.png)

**Comment by MeKugel** [comment]
Scheint ein temporäres Problem mit nur diesem Tweet gewesen zu sein. Gerade getestet und der Tweet wird richtig dargestellt (über Extension und Collector eingesammelt)
