### ISSUE TITLE
Facebook-Caroussel als Slideshow importieren

### ISSUE THREAD

**Issue by joachimgo** [flypsite/general#99]
Die folgenden Posts enthalten mehrere Bilder. Sie werden momentan mit einem Bild (dem letzten) und einem Text (Headline: Text des ersten Bildes, Text: posttext) importiert.

https://www.facebook.com/textilenetwork/posts/1381022428574602
https://www.facebook.com/textilenetwork/posts/1368169893193189

Gut wäre, wenn wir wie beim Album eine Slideshow erzeugen würden; alle Bilder importieren, den Posttext als Text auf die Bilder und den Link ebenfalls auf alle Bilder packen würden.

(Caroussel ist wohl primär eine Werbeform; die Texte bei den einzelnen Elementen sind nicht durch den Facebook-Autor festgelegt, sondern stammen von der verlinkten Seite).

**Comment by MeKugel** [comment]
Ist auf Staging eingebaut

**Comment by joachimgo** [comment]
Ist jetzt auch im Livesystem.

Bitte noch korrigieren/kommunizieren:
Beide Beispiele sehen aus, als hätten sie drei Bilder. Ich würde erwarten, dass das erste Bild das Titelbild der Slideshow wird.
Was ich sehe: Titelbild ist das Usericon (oder Bild 3?). In der Slideshow sind nur zwei Bilder. Bitte Rücksprache.

**Comment by MeKugel** [comment]
Facebook gibt Caroussel das Profilbild der postenden Seite als Titelbild des Posts (full_picture) zurück (analog bei Slideshows das erste Bild der Slideshow). Die letzte Kachel (das letzte Bild) eines Caroussels ist ein Link zur werbenden Seite und wird per API nicht zurückgeliefert.
